Replaced xmlhttprequest by request-promise-native
vinotion/visense-tools pull request #2
Opened 2017-05-10 15:56 UTC by martinp36

Also,
- Request results are automatically parsed to JSON-format,
- WebSocketConnection close() throws when no connection was opened,
- Native implementation of Promise is now used,
- Tests yielding uncaught rejection warnings have been fixed,
- QUnit testrunner API to run tests.

2017-05-10 19:57 UTC, vinotion commented on lib/authentication.js
> +  {
Fix indentation.

2017-05-10 19:58 UTC, vinotion commented on lib/authentication.js
> +               && (body.data.clientToken !== 'undefined'))
`typeof`

2017-05-10 20:00 UTC, vinotion commented on lib/authentication.js
> +               && (body.data.clientToken !== 'undefined'))
And also, check if `data` itself exists, otherwise the dereference of `clientToken` will lead to a JavaScript error.

2017-05-10 20:00 UTC, vinotion commented on lib/authentication.js
> +               && (response.statusCode == 200)
`===`

2017-05-10 20:00 UTC, vinotion commented on lib/authentication.js
> +              _sessionToken = body.data.clientToken
Add ending semicolon.

2017-05-10 20:01 UTC, vinotion commented on lib/authentication.js
> +               && (response.statusCode == 200)
`===`

2017-05-10 20:01 UTC, vinotion commented on lib/authentication.js
> +               && (typeof body.message.success !== 'undefined'))
Check if `message` itself exists, see remark above.

2017-05-10 20:04 UTC, vinotion commented on lib/authentication.js
> +  let _defaultOptions =
`const`

2017-05-10 20:04 UTC, vinotion commented on lib/configuration-adapter.js
> +  {
Fix indentation.

2017-05-10 20:06 UTC, vinotion commented on package.json
> +    "request": "~2.81.0",
Is this still needed if request-promise-native is already included?

2017-05-10 20:07 UTC, vinotion commented on tests/all-tests.js
> +    code: "./index.js",
Use single quotes (at many places).

2017-05-10 20:08 UTC, vinotion commented on tests/all-tests.js
> +  {
Indent one level deeper (so that `]` doesn't touch the margin).

2017-05-10 20:12 UTC, vinotion commented on tests/authentication-tests.js
> +        return (typeof x.signIn({ username: 'dsfnjskjn3', password: 'kjfuisqh3' }).catch(error => {}) === 'object');
What's the function of the named error? Wouldn't `() => {}` or `null` suffice?

2017-05-10 20:12 UTC, vinotion commented on tests/authentication-tests.js
> +        return (typeof x.signOut().catch(error => {}) === 'object');
Ditto, see remark above.

2017-05-10 20:12 UTC, vinotion commented on tests/authentication-tests.js
> +        return (typeof x.verify().catch(error => {}) === 'object');
Ditto, see remark above.

2017-05-10 20:13 UTC, vinotion commented on tests/configuration-adapter-tests.js
> +        return (typeof x.queryParameter('').catch(error => {}) === 'object');
Ditto, see remark above (multiple places).

2017-05-10 20:13 UTC, vinotion commented on tests/visense-system-tests.js
> +        return (typeof x.queryProductName().catch(error => {}) === 'object');
Ditto, see remark above (multiple places).

2017-05-10 20:13 UTC, vinotion commented on tests/websocket-connection-tests.js
> +        return (typeof x.open().catch(error => {}) === 'object');
Ditto, see remark above.

2017-05-10 20:15 UTC, vinotion commented on tests/websocket-connection-tests.js
> +      }, 'Close when the WebSocketConnection is not opened yet');
WebSocket connection

2017-05-11 06:45 UTC, martinp36 commented on lib/authentication.js
lalla

2017-05-11 08:04 UTC, vinotion requested changes

2017-05-11 08:04 UTC, vinotion commented on lib/authentication.js
>    checkUtils.checkSocketAddress(socketAddress);
Hoi

2017-05-11 08:26 UTC, martinp36 reviewed
Fixed everything.

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +  let _defaultOptions =
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +               && (response.statusCode == 200)
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +               && (body.data.clientToken !== 'undefined'))
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +              _sessionToken = body.data.clientToken
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +               && (response.statusCode == 200)
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +               && (typeof body.message.success !== 'undefined'))
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/configuration-adapter.js
> +  {
Fixed

2017-05-11 08:26 UTC, martinp36 commented on lib/authentication.js
> +  {
Fixed

2017-05-11 08:26 UTC, martinp36 commented on package.json
> +    "request": "~2.81.0",
It is

2017-05-11 08:26 UTC, martinp36 commented on tests/all-tests.js
> +  {
Fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/authentication-tests.js
> +        return (typeof x.signIn({ username: 'dsfnjskjn3', password: 'kjfuisqh3' }).catch(error => {}) === 'object');
`null` does not, `()=>{}` does. its fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/authentication-tests.js
> +        return (typeof x.signOut().catch(error => {}) === 'object');
fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/authentication-tests.js
> +        return (typeof x.verify().catch(error => {}) === 'object');
fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/configuration-adapter-tests.js
> +        return (typeof x.queryParameter('').catch(error => {}) === 'object');
fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/visense-system-tests.js
> +        return (typeof x.queryProductName().catch(error => {}) === 'object');
fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/websocket-connection-tests.js
> +        return (typeof x.open().catch(error => {}) === 'object');
fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/websocket-connection-tests.js
> +      }, 'Close when the WebSocketConnection is not opened yet');
Fixed

2017-05-11 08:26 UTC, martinp36 commented on tests/all-tests.js
> +    code: "./index.js",
Fixed

2017-05-11 08:33 UTC, vinotion approved these changes

2017-05-11 08:33 UTC, merged